name: CI Checks

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - main


jobs:

  backend-check:
    name: Backend Check
    runs-on: ubuntu-latest

    env:
        FRONTEND_URL: ${{ secrets.FRONTEND_URL }}


    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Verify backend imports
        run: python -c "import main; print('Backend OK')"


  frontend-check:
    name: Frontend Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build